### ISSUE TITLE
[Bug] rstest framework conflicts with hard coded crypto provider

### ISSUE THREAD

**Issue by raphaelrobert** [openmls/openmls#600]
This is currently the case when using the `evercrypt` backend in `src/messages/tests/test_welcome.rs`.

**Comment by franziskuskiefer** [comment]
I can't reproduce this. Signing works fine for me. But I can't test anything else.
Some tests, like this one
https://github.com/openmls/openmls/blob/04401ee221cb5584e051e035169cae113251c1c3/openmls/src/messages/tests/test_welcome.rs#L26
as well as others
https://github.com/openmls/openmls/blob/04401ee221cb5584e051e035169cae113251c1c3/openmls/tests/test_encoding.rs#L16
ignore the test suites. Picking an AES test suite with evercrypt will fail on non-x64 (or old) machines.

So it's expected that these tests fail on my M1.

**Comment by raphaelrobert** [comment]
The issue happened on linux x64_86, I'll try to reproduce it and will post more details.

**Comment by raphaelrobert** [comment]
I could reproduce the error and I get the following output:

```
running 6 tests
test messages::tests::test_welcome::test_welcome_msg::case_1_rust_crypto_MLS10_128_DHKEMX25519_AES128GCM_SHA256_Ed25519 ... ok
test messages::tests::test_welcome::test_welcome_msg::case_2_rust_crypto_MLS10_128_DHKEMP256_AES128GCM_SHA256_P256 ... ok
test messages::tests::test_welcome::test_welcome_msg::case_3_rust_crypto_MLS10_128_DHKEMX25519_CHACHA20POLY1305_SHA256_Ed25519 ... ok
test messages::tests::test_welcome::test_welcome_msg::case_4_evercrypt_MLS10_128_DHKEMX25519_AES128GCM_SHA256_Ed25519 ... FAILED
test messages::tests::test_welcome::test_welcome_msg::case_6_evercrypt_MLS10_128_DHKEMX25519_CHACHA20POLY1305_SHA256_Ed25519 ... FAILED
test messages::tests::test_welcome::test_welcome_msg::case_5_evercrypt_MLS10_128_DHKEMP256_AES128GCM_SHA256_P256 ... ok

failures:

---- messages::tests::test_welcome::test_welcome_msg::case_4_evercrypt_MLS10_128_DHKEMX25519_AES128GCM_SHA256_Ed25519 stdout ----
-------------- TEST START --------------
thread 'messages::tests::test_welcome::test_welcome_msg::case_4_evercrypt_MLS10_128_DHKEMX25519_AES128GCM_SHA256_Ed25519' panicked at 'Error signing GroupInfo: CryptoError(CryptoLibraryError)', src/messages/tests/test_welcome.rs:59:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- messages::tests::test_welcome::test_welcome_msg::case_6_evercrypt_MLS10_128_DHKEMX25519_CHACHA20POLY1305_SHA256_Ed25519 stdout ----
-------------- TEST START --------------
thread 'messages::tests::test_welcome::test_welcome_msg::case_6_evercrypt_MLS10_128_DHKEMX25519_CHACHA20POLY1305_SHA256_Ed25519' panicked at 'Error signing GroupInfo: CryptoError(CryptoLibraryError)', src/messages/tests/test_welcome.rs:59:10


failures:
    messages::tests::test_welcome::test_welcome_msg::case_4_evercrypt_MLS10_128_DHKEMX25519_AES128GCM_SHA256_Ed25519
    messages::tests::test_welcome::test_welcome_msg::case_6_evercrypt_MLS10_128_DHKEMX25519_CHACHA20POLY1305_SHA256_Ed25519

test result: FAILED. 4 passed; 2 failed; 0 ignored; 0 measured; 332 filtered out; finished in 0.09s

error: test failed, to rerun pass '--lib'

```

So it seems that signing with `Ed25519` doesn't work with `evercrypt` in this instance.

STR:
 - Comment out lines 23 & 25 in `src/messages/tests/test_welcome_msg.rs`
 - run `cargo test test_welcome_msg` on x64-86 linux

**Comment by raphaelrobert** [comment]
Well spotted!

**Comment by franziskuskiefer** [comment]
Let's use this issue to fix all of these issues. A quick search shows this

```
34 results - 18 files

openmls/benches/benchmark.rs:
  19                      || {
  20:                         let crypto = &OpenMlsRustCrypto::default();
  21                          CredentialBundle::new(

  29                      |credential_bundle: CredentialBundle| {
  30:                         let crypto = &OpenMlsRustCrypto::default();
  31                          KeyPackageBundle::new(

openmls/src/ciphersuite/aead.rs:
  148      fn test_xor() {
  149:         let crypto = &OpenMlsRustCrypto::default();
  150          let reuse_guard: ReuseGuard = ReuseGuard::from_random(crypto);

openmls/src/ciphersuite/tests/test_ciphersuite.rs:
  84  fn supported_ciphersuites() {
  85:     let backend = &OpenMlsRustCrypto::default();
  86  

openmls/src/group/tests/kat_messages.rs:
  51  pub fn generate_test_vector(ciphersuite: &'static Ciphersuite) -> MessagesTestVector {
  52:     let crypto = OpenMlsRustCrypto::default();
  53      let ciphersuite_name = ciphersuite.name();

openmls/src/group/tests/kat_transcripts.rs:
  50  pub fn generate_test_vector(ciphersuite: &'static Ciphersuite) -> TranscriptTestVector {
  51:     let crypto = OpenMlsRustCrypto::default();
  52      // Generate random values.

openmls/src/messages/tests/test_welcome.rs:
  24      // Only use RustCrypto for now
  25:     let backend = &OpenMlsRustCrypto::default();
  26      test_welcome_message_with_version(ciphersuite, backend, Config::supported_versions()[0]);

  33  ) {
  34:     let crypto = OpenMlsRustCrypto::default();
  35      // We use this dummy group info in all test cases.

openmls/src/schedule/kat_key_schedule.rs:
   88  ) {
   89:     let crypto = OpenMlsRustCrypto::default();
   90      let tree_hash = crypto

  182      use crate::ciphersuite::HpkePublicKey;
  183:     let crypto = OpenMlsRustCrypto::default();
  184  

  320      };
  321:     let crypto = OpenMlsRustCrypto::default();
  322      log::debug!("Testing test vector for ciphersuite {:?}", ciphersuite);

openmls/src/test_utils/mod.rs:
  101  #[rstest(backend,
  102:     case::rust_crypto(&OpenMlsRustCrypto::default()),
  103    )

  116  #[rstest(backend,
  117:     case::rust_crypto(&OpenMlsRustCrypto::default()),
  118      case::evercrypt(&evercrypt_backend::OpenMlsEvercrypt::default()),

  147  #[rstest(ciphersuite, backend,
  148:     case::rust_crypto_MLS10_128_DHKEMX25519_AES128GCM_SHA256_Ed25519(Config::ciphersuite(CiphersuiteName::MLS10_128_DHKEMX25519_AES128GCM_SHA256_Ed25519).expect("Ciphersuite not supported."), &OpenMlsRustCrypto::default()),
  149:     case::rust_crypto_MLS10_128_DHKEMP256_AES128GCM_SHA256_P256(Config::ciphersuite(CiphersuiteName::MLS10_128_DHKEMP256_AES128GCM_SHA256_P256).expect("Ciphersuite not supported."), &OpenMlsRustCrypto::default()),
  150:     case::rust_crypto_MLS10_128_DHKEMX25519_CHACHA20POLY1305_SHA256_Ed25519(Config::ciphersuite(CiphersuiteName::MLS10_128_DHKEMX25519_CHACHA20POLY1305_SHA256_Ed25519).expect("Ciphersuite not supported."), &OpenMlsRustCrypto::default()),
  151    )

  169  #[rstest(ciphersuite, backend,
  170:     case::rust_crypto_MLS10_128_DHKEMX25519_AES128GCM_SHA256_Ed25519(Config::ciphersuite(CiphersuiteName::MLS10_128_DHKEMX25519_AES128GCM_SHA256_Ed25519).expect("Ciphersuite not supported."), &OpenMlsRustCrypto::default()),
  171:     case::rust_crypto_MLS10_128_DHKEMP256_AES128GCM_SHA256_P256(Config::ciphersuite(CiphersuiteName::MLS10_128_DHKEMP256_AES128GCM_SHA256_P256).expect("Ciphersuite not supported."), &OpenMlsRustCrypto::default()),
  172:     case::rust_crypto_MLS10_128_DHKEMX25519_CHACHA20POLY1305_SHA256_Ed25519(Config::ciphersuite(CiphersuiteName::MLS10_128_DHKEMX25519_CHACHA20POLY1305_SHA256_Ed25519).expect("Ciphersuite not supported."), &OpenMlsRustCrypto::default()),
  173      case::evercrypt_MLS10_128_DHKEMX25519_AES128GCM_SHA256_Ed25519(Config::ciphersuite(CiphersuiteName::MLS10_128_DHKEMX25519_AES128GCM_SHA256_Ed25519).expect("Ciphersuite not supported."), &evercrypt_backend::OpenMlsEvercrypt::default()),

openmls/src/test_utils/test_framework/mod.rs:
  134              // For now, everyone supports all ciphersuites.
  135:             let crypto = OpenMlsRustCrypto::default();
  136              let mut credentials = HashMap::new();

openmls/src/tree/tests_and_kats/kats/kat_encryption.rs:
  299      let ciphersuite_name = ciphersuite.name();
  300:     let crypto = OpenMlsRustCrypto::default();
  301      let epoch_secret = crypto

openmls/src/tree/tests_and_kats/kats/kat_tree_kem.rs:
  330  
  331:     let crypto = OpenMlsRustCrypto::default();
  332  

openmls/src/tree/tests_and_kats/unit_tests/test_hashes.rs:
  6  fn test_parent_hash() {
  7:     let crypto = OpenMlsRustCrypto::default();
  8      for ciphersuite in Config::supported_ciphersuites() {

openmls/src/tree/tests_and_kats/unit_tests/test_private_tree.rs:
  18  fn setup(ciphersuite: &Ciphersuite, len: usize) -> (KeyPackageBundle, LeafIndex, Vec<NodeIndex>) {
  19:     let crypto = OpenMlsRustCrypto::default();
  20      let credential_bundle = CredentialBundle::new(

  82      const PATH_LENGTH: usize = 33;
  83:     let crypto = OpenMlsRustCrypto::default();
  84      for ciphersuite in Config::supported_ciphersuites() {

openmls/src/tree/tests_and_kats/unit_tests/test_resolution.rs:
  12  fn test_exclusion_list() {
  13:     let crypto = OpenMlsRustCrypto::default();
  14      for ciphersuite in Config::supported_ciphersuites() {

  95  fn test_original_child_resolution() {
  96:     let crypto = OpenMlsRustCrypto::default();
  97      for ciphersuite in Config::supported_ciphersuites() {

openmls/src/tree/tests_and_kats/unit_tests/test_secret_tree.rs:
   12  fn test_boundaries() {
   13:     let crypto = OpenMlsRustCrypto::default();
   14      for ciphersuite in Config::supported_ciphersuites() {

  114  fn increment_generation() {
  115:     let crypto = OpenMlsRustCrypto::default();
  116      const SIZE: usize = 100;

  171  fn secret_tree() {
  172:     let crypto = OpenMlsRustCrypto::default();
  173      let ciphersuite = &Config::supported_ciphersuites()[0];

openmls/src/tree/tests_and_kats/unit_tests/test_sender_ratchet.rs:
   9  fn test_ratchet_generations() {
  10:     let crypto = &OpenMlsRustCrypto::default();
  11  

openmls/src/tree/tests_and_kats/unit_tests/test_tree_truncation.rs:
  14  fn test_trim() {
  15:     let crypto = OpenMlsRustCrypto::default();
  16      // Build a list of nodes, for which we need credentials and key package bundles

openmls/src/tree/tests_and_kats/unit_tests/test_treemath.rs:
  35  fn test_tree_hash() {
  36:     let crypto = OpenMlsRustCrypto::default();
  37      fn create_identity(id: &[u8], ciphersuite_name: CiphersuiteName) -> KeyPackageBundle {
  38:         let crypto = OpenMlsRustCrypto::default();
  39          let signature_scheme = SignatureScheme::from(ciphersuite_name);
```

**Comment by franziskuskiefer** [comment]
Re-opening because there are more issues https://github.com/openmls/openmls/issues/600#issuecomment-989547339
